"""tables altered

Revision ID: 4a5a88899296
Revises: 
Create Date: 2025-04-18 21:10:20.456169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5a88899296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('demo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
