"""Add additional fields to User model

Revision ID: 8336afe2b619
Revises: 4a5a88899296
Create Date: 2025-04-18 21:51:36.525750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8336afe2b619'
down_revision = '4a5a88899296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('friend_request_setting', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('friend_request_setting')
        batch_op.drop_column('profile_visibility')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('github')
        batch_op.drop_column('skills')
        batch_op.drop_column('college')

    # ### end Alembic commands ###
